Add mac and linux script
slashrelativepath/relativepath-cycle-4 pull request #2
Opened 2023-06-27 22:30 UTC by topher4D

2023-06-27 22:35 UTC, paulh6819 requested changes

2023-06-27 22:35 UTC, paulh6819 commented on myscript.sh
> +x#!/bin/zsh
please remove this "X"

2023-06-27 22:35 UTC, paulh6819 commented on myscript.sh
> +  /bin/bash -c "$(curl -fsSL
line 12 and 13 have an unnecessary line break. please fix thank you

2023-06-27 22:35 UTC, paulh6819 commented on myscript.sh
> +# then echo "nano is already installed"
confused about how this code ended. Please elaborate.

2023-06-28 22:19 UTC, stephenlauck approved these changes

2023-06-28 22:21 UTC, JoshRodstein approved these changes
LGTM

2023-06-28 22:24 UTC, paulh6819 approved these changes

2023-06-28 22:24 UTC, merged